name: Docker

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push the images
        run: |
          IMAGE_NAME="dphadatare/phpexcel"
          for versionFilePath in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} ${{ github.event.before }} | grep "Dockerfile");
          do
            if [ "${versionFilePath}" != "Dockerfile.template" ]; then

              folder=${versionFilePath%"/Dockerfile"}
              folderName=${folder#*/}
              versionName="${folderName////-}"

              tmpName="image-$RANDOM"
              docker build $folder --file $folder/Dockerfile --tag $tmpName
              IMAGE_ID=$IMAGE_NAME
              VERSION=$versionName

              echo IMAGE_ID=$IMAGE_ID
              echo VERSION=$VERSION

              docker tag $tmpName $IMAGE_ID:$VERSION
              docker push $IMAGE_ID:$VERSION
            fi
          done;
